import type { AttachmentResponse } from '@/types/attachment';
import type { CategoryResponse } from '@/types/category';
import type { Address, BaseEntity } from '@/types/common';

export type CreateSiteRequest = Readonly<{
  name: string;
  domainName: string;
  description?: string | null;
  distributionCode?: string | null;
  searchEngineExposed?: boolean | null;
  imageExposed?: boolean | null;
  themeColor?: string | null;
  backgroundColor?: string | null;
  tags?: string | null;
  address?: Address | null;
  contactNumber?: string | null;
  intro?: string | null;
  content?: string | null;
  profileImage?: File | null;
  backgroundImage?: File | null;
  profileImageSizeValid?: boolean | null;
  backgroundImageSizeValid?: boolean | null;
}>;

export type SiteResponse = Readonly<{
  id: string;
  createdBy?: string | null;
  createdIp?: string | null;
  createdDate?: string | null;
  lastModifiedBy?: string | null;
  lastModifiedIp?: string | null;
  lastModifiedDate?: string | null;
  parentId?: string | null;
  parent?: SiteResponse | null;
  children?: SiteResponse[];
  name?: string | null;
  domainName?: string | null;
  description?: string | null;
  distributionCode?: string | null;
  searchEngineExposed?: boolean | null;
  imageExposed?: boolean | null;
  themeColor?: string | null;
  backgroundColor?: string | null;
  tags?: string | null;
  address?: Address | null;
  contactNumber?: string | null;
  intro?: string | null;
  content?: string | null;
  categories?: CategoryResponse[];
  attachments?: AttachmentResponse[];
  profileImage?: AttachmentResponse | null;
  backgroundImage?: AttachmentResponse | null;
  root?: boolean | null;
  baseModel?: BaseEntity | null;
}>;
