import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { cookies } from 'next/headers';

import { APPLICATION_NAME } from '@/lib/application-constants.ts';
import { NAVIGATION_COLLAPSED_COOKIE_KEY, NAVIGATION_POSITION_COOKIE_KEY } from '@/lib/navigation-preferences';
import { getSiteContext } from '@/lib/site';
import { createSiteContext } from '@/lib/site-context';
import { GlobalShell } from '@/components/layout/global-shell';
import { ThemeScript } from '@/components/theme/theme-script';
import { ServiceWorkerRegistration } from '@/app/service-worker-registration';
import { SiteContextProvider } from '@/app/site-context-provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: `/manifest.json`
};

const domainName = `${APPLICATION_NAME}.seesaw.me.kr`;

export default async function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  const site = await getSiteContext(domainName);
  metadata.title = `홈 | ${site.name}`;
  const siteContext = createSiteContext(site);
  const cookieStore = await cookies();
  const navigationPositionCookie = cookieStore.get(NAVIGATION_POSITION_COOKIE_KEY)?.value;
  const navigationCollapsedCookie = cookieStore.get(NAVIGATION_COLLAPSED_COOKIE_KEY)?.value;
  const initialNavigationPosition = navigationPositionCookie === 'right' ? 'right' : 'left';
  const initialNavigationCollapsed = navigationCollapsedCookie === 'true';

  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} suppressHydrationWarning>
      <head>
        <ThemeScript />
        <title>{`홈 | ${site.name}`}</title>
      </head>
      <body className="flex min-h-full flex-col">
        <SiteContextProvider siteContext={siteContext}>
          <GlobalShell initialNavigationCollapsed={initialNavigationCollapsed} initialNavigationPosition={initialNavigationPosition}>
            {children}
          </GlobalShell>
        </SiteContextProvider>
        <ServiceWorkerRegistration authenticated={false} siteId={site.id} siteName={site.name} themeColor={site.themeColor} />
      </body>
    </html>
  );
}
